### PR TITLE
fix: auto adapt small resolution screen

### LINKED ISSUE #15: [Bug]Not all content can be displayed on a smaller resolution monitor
Like this:

image

I can neither click the title bar nor see the upside button.

### PR DESCRIPTION
**Pull request by mzwing**
This PR should fix #15 .

### CODE REVIEW

**Comment by mzwing** [comment]
Since I haven't used wails and Go at all before, you'd better check it out.
Tested on my computer with no issues, and the css (probably) has no issues either.
The code I wrote is a bit ugly, but as a person who has never used Go (only knows `package main`), I tried my best😭

**Comment by Cyberhan123** [comment]
Great! Thank you for your contribution.

**Comment by Cyberhan123** [comment]
Great! Thank you for your contribution.

**Comment by Cyberhan123** [comment]
great，thx your contribute

**Pull request merged**
